# Generated by Django 4.2.2 on 2023-06-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='instrumentcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
